# Generated by Django 6.0 on 2025-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="invite_code",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
