# Generated by Django 6.0 on 2025-12-18 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_household_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="household",
            name="invite_code",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
