# Generated by Django 6.0 on 2025-12-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_alter_budget_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="is_active",),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
