# Generated by Django 6.0 on 2025-12-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0007_remove_category_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
